### PR TITLE
Change how `extends` work

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
## Proposal
Recently, it came to my attention that clients don't really like the way `Extends` is structured - i.e. the type that we're describing has all the properties of parent (in the meaning - the ones that are extended) types.

Consider this code:
```csharp
public interface A { public int PropA { get; set; } }
public class B { public int PropB { get; set; } }
public class C : B, A { public int PropA { get; set; } public int PropC { get; set; } }
```

In the "old" way, the `C` type would have these properties: `PropA` (implemented directly, but required by the interface), `PropB` (inherited from `B`) and `PropC`. 

In the "new" way, the `C` type would have only `PropC` because it is directly implemented by the type. `PropA` and `PropB` are described in up in the chain.

## Reasoning
The old way `Extended` worked was more like interfaces. This is quite awkward considering this is mostly _data_ protocol, not programming language. The new way works more like mixins/multi-inheritance, which seems to be easier to reason about and implement in client languages (TS specifically).

This solution also does not prevent clients from generating types that are really a sum of extended types. It only needs a little bit more code as the union needs to be handled there.

The "old" solution also allows clients to work like this, but it is more cumbersome - instead of doing union, you need to exclude properties from all the types that are being extended. It is easier to do on the `server` side, hence the change.

## Problems
Roslyn, unfortunately, does not give us information that the `IPropertySymbol` is required by/connected to an interface. We need to do the resolution logic ourselves (or is there a way in Roslyn and I just can't find it?). IMO this is not really a problem, as the logic is quite easy (just a name match), but we need to disallow explicit interface implementations (which I would opt to do anyway).

## Next steps
Considering that I am not really confident which of these two is better - what are your thoughts?

## Notes
This is a draft PR not only because I don't know which way to choose, but also the code needs some improvements.

### CODE REVIEW

**Comment by shilangyu** [comment]
For the dart generator the old way is much easier to implement. In fact, if the new way would be introduced the dart generator would end up simulating the old way anyways. Reason being that all fields have to be initialized during construction, so the dart generator would have to resolve all inherited fields anyways (since the Dart generator operates on instances, not just types like the Typescript one). 

If the Typescript generator finds this solution better, then I'm ok with it.

Q: what happens with overriden fields? Are they allowed? With the old way, C# generator resolved all fields and clients would just copy over the fields without any logic. If overriding will be allowed now, we would need to ensure all clients adhere to the same overriding rules.

**Comment by jakubfijalkowski** [comment]
> Q: what happens with overriden fields? Are they allowed?

Overriding, shadowing and explicit interface implementation will be explicitly rejected. Let's keep it basic and disallow as much C# "programming" features as reasonable.

> If the Typescript generator finds this solution better, then I'm ok with it.

Yeah, TS generator seems to prefer "the new way", esp. that this distinction allows much more implementations (and seems to be widely understood).

Thanks for your input!

**Comment by konowrockis** [comment]
I'd like to get back to that. Another issue that exists with current solution is comments generation on properties. The comments are only attached to original property definition. So when anything extends an interface with comment on property the information is lost in the new flattened interface.

**Comment by jakubfijalkowski** [comment]
That's mostly a bug, but I want to finish this PR sometime next week, so it will be "fixed".

**Review by shilangyu — APPROVED** [review]

**Review by konowrockis — APPROVED** [review]

**Pull request merged**
